### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by MrSnoop** [tiaguinho/mongodb-cakephp3#1]
Hi!
Thanks for your plugin. 
But I am wondering how to install the plugin. You suggest just to require via composer cakephp/elastic search but after that: what to do? 
Enabling the plugin won´t work unless there is a plugin in vendor folder which also then should be autoloaded right?

**Comment by tiaguinho** [comment]
Sorry @MrSnoop, the right way to install is running `composer require hayko/mongodb`. 

I fixed the documentation too.

Cheers
