### ISSUE TITLE
Getting default Database connection always

### ISSUE THREAD

**Issue by basantk** [tiaguinho/mongodb-cakephp3#10]
i have two or more Datasources  connection i wan a connection from  default to other and test datasource for mongo only.
so how can i do that.
and i want to work with mysql and mongo db both.

**Comment by tiaguinho** [comment]
Inside your initialize method, set the name of the connection you want.
Will be like this

```php
public function initialize(array $config) {
    $config['connection'] = "myconnection";
    parent::initialize($config);
}
```

**Comment by basantk** [comment]
Thanks

**Comment by basantk** [comment]
how can i use aggregation in momgoDB like

**Comment by tiaguinho** [comment]
This was not implemented yet.
