### ISSUE TITLE
Error: Class '\MongoDB' not found 

### ISSUE THREAD

**Issue by apurv3039** [tiaguinho/mongodb-cakephp3#13]
Hello Tiagu,

I implementing your plugin in cakephp3.2.12 version, but i m facing the following problem:
Error: Class '\MongoDB' not found 
File D:\xampp\htdocs\sbi\vendor\hayko\mongodb\src\Database\Driver\Mongodb.php 
Line: 152,

**Comment by tiaguinho** [comment]
Hi @apurv3039, check the version of your mongo driver.
This driver was created for the new driver implementation.

https://pecl.php.net/package/mongodb
