### ISSUE TITLE
Not authorized to connect

### ISSUE THREAD

**Issue by juancarielo** [tiaguinho/mongodb-cakephp3#20]
What do I choose Auth Mechanism?

I tried default config (MONGODB-CR) to connect using Robo 3T like database manager, but it returns "Not authorized to connect". When I switch this to SCRAM-SHA-1 I get a success.

How do I change this auth mechanism in your plugin config?

Thanks!

**Comment by abdelatnova** [comment]
see https://github.com/tiaguinho/mongodb-cakephp3/pull/21
