### ISSUE TITLE
No efficient way of counting?

### ISSUE THREAD

**Issue by johnjcamilleri** [tiaguinho/mongodb-cakephp3#28]
I wanted an equivalent of Mongo's `count` command, which can return a result count without having to perform an actual find (which can be much slower). I couldn't find it in this library, so I hacked together this, added to **src/ORM/Table.php**:

```php
/**
 * count documents
 *
 * @param array $options
 * @return int
 * @access public
 */
public function count($options = [])
{
    $query = new MongoFinder($this->__getCollection(), $options);
    return $query->connection()->count();
}
```

Not sure if I've missed something, seems like this functionality should be standard?

**Comment by tiaguinho** [comment]
Hi @johnjcamilleri, can you open a PR with this change so I can merge with the master of the project?

Thanks!

**Comment by tiaguinho** [comment]
Thank you for your contribution @johnjcamilleri
