### ISSUE TITLE
Error: Class 'Mongo' not found

### ISSUE THREAD

**Issue by kawaiidesune** [tiaguinho/mongodb-cakephp3#4]
So, when I went to implement this plugin, I got this error message in CakePHP...

```
Error: Class 'Mongo' not found 
File /var/www/llamacast/vendor/hayko/mongodb/src/Database/Connection.php 
Line: 112
```

I find it peculiar because on line 112 of /src/Database/Connection.php, it is a new instance of Mongodb being instantiated, not "Mongo". 😖

**Comment by tiaguinho** [comment]
which version of mongo drive do you use?

**Comment by shraddhabanerjee** [comment]
Hi @tiaguinho,

I am getting the following error 

Class '\MongoDB' not found Error
Documentation API
Error in: ROOT/vendor/hayko/mongodb/src/Database/Driver/Mongodb.php, line 152

If you want to customize this error message, create src/Template/Error/error500.ctp
toggle vendor stack frames

    ⟩ Hayko\Mongodb\Database\Driver\Mongodb->connect ROOT/vendor/hayko/mongodb/src/Database/Connection.php, line 126

MongoDB shell version: 3.2.15
CakePHP 3

Kindly request you yo help in this issue.
