### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ghost** [tiaguinho/mongodb-cakephp3#6]
I'm getting an error with 'composer require hayko/mongodb'

[InvalidArgumentException]  
  Could not find package hayko/mongodb at any version for your minimum-stability (beta). Check the package spelling or your minimum-stability

**Comment by tiaguinho** [comment]
Hi @rroja 

Try this.

``` bash
composer require hayko/mongodb dev-master
```

**Comment by hm-91** [comment]
Hi @tiaguinho, I'm also getting errors after Installation

`Use of undefined constant MONGOD
B_VERSION - assumed 'MONGODB_VERSION' [ROOT/vendor/hayko/mongodb/src/Database/Connection.php, line 109]`


`Error: Class '\MongoDB' not found 
File /Applications/XAMPP/xamppfiles/htdocs/gideon/vendor/hayko/mongodb/src/Database/Driver/Mongodb.php 
Line: 146`

![screen shot 2016-12-14 at 12 17 19 pm](https://cloud.githubusercontent.com/assets/1847035/21169460/51119d86-c1f7-11e6-8605-8897391703ae.png)
