### ISSUE TITLE
Installation Issue in Cakephp 3.3.10

### ISSUE THREAD

**Issue by hm-91** [tiaguinho/mongodb-cakephp3#8]
Hi @tiaguinho, I'm getting below errors after installing in Cakephp 3.3.10

`Use of undefined constant MONGODB_VERSION - assumed 'MONGODB_VERSION' [ROOT/vendor/hayko/mongodb/src/Database/Connection.php, line 109]`

`Error: Class '\MongoDB' not found File /Applications/XAMPP/xamppfiles/htdocs/gideon/vendor/hayko/mongodb/src/Database/Driver/Mongodb.php Line: 146`

![screen shot 2016-12-14 at 12 17 19 pm](https://cloud.githubusercontent.com/assets/1847035/21170291/d232b2c2-c1fe-11e6-91da-37cac464a0a0.png)

**Comment by tiaguinho** [comment]
Hi @hm-91, you install mongodb drive for XAMPP?
If you do, which version of drive?

**Comment by hm-91** [comment]
@tiaguinho, Thanks for the reply

Sorry, My mistake I didn't install mongodb PHP driver for XAMPP.  It works now.

I have also defined mongodb version on app.php
`define(MONGODB_VERSION, "3.2.11");`
